url: https://spiritify.com.br
baseurl: /

# Site settings
title: Spiritify - O Spotify Segundo o Espiritismo
email: equipe.spiritify@gmail.com
description: "Website do Spiritify, canal do Spotify e do Deezer dedicado à música espírita."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/spiritifybr
  - title: facebook
    url: https://www.facebook.com/SpiritifyBR
  - title: instagram
    url: https://www.instagram.com/spiritifybr

# Build settings
markdown: kramdown
permalink: pretty
